apiVersion: v1
kind: PersistentVolume
metadata:
  name: issuance-pv
  namespace: kube-credential
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/issuance
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: verification-pv
  namespace: kube-credential
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/verification
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: issuance-pvc
  namespace: kube-credential
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: verification-pvc
  namespace: kube-credential
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage